apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amunity
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:j-kowal/apkka.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: amunity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
